version: '3.8'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env.example
    ports:
      - '3001:3001'
  frontend:
    build: ./frontend
    env_file: ./frontend/.env.example
    ports:
      - '3000:3000'

